### PR TITLE
Fix ignored project id from the config

### PR DESCRIPTION
**Pull request by simplylizz**
Also update google cloud libs version, because BQ library had ignored project id as well prior to 1.55.0 version:
https://github.com/googleapis/java-bigquery/commit/bd26a54c62f2dfbea532311003591e62dcdc0ad9

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by simplylizz** [comment]
I signed it.

**Comment by simplylizz** [comment]
Also regarding API version update: I'm not sure if I should update it to the most recent version or to the closest possible, so I choose the second option.

**Comment by dilyand** [comment]
Thanks very much for this contribution @simplylizz . We're just wrapping up the 0.5.0 release, so this will probably go into the next release after that.

**Comment by dilyand** [comment]
Closes https://github.com/snowplow-incubator/snowplow-bigquery-loader/issues/104.

**Comment by simplylizz** [comment]
Rebased on top of master to eliminate conflicts.

**Comment by dilyand** [comment]
@simplylizz Did anything happen to the repo you opened this PR from? I can't seem to find it so I can't cherry-pick your changes.

**Comment by simplylizz** [comment]
Hmm, yeah, I've re-created it as a private repo and merged all required to me changes. Didn't know that this will affect public PRs.

**Comment by simplylizz** [comment]
Do you need any help with this?

**Comment by dilyand** [comment]
I can easily recreate the changes but sadly your name will not be on the commit.

**Comment by simplylizz** [comment]
No problem, that's really not an enormous contribution. :)

**Comment by simplylizz** [comment]
@dilyand I see that you did merge this changes so perhaps this PR could be closed.

**Pull request closed without merging**
